image: maven:3.8.5-openjdk-17

stages:
  - test

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests=false"

test_job:
  stage: test
  script:
    - mvn clean verify
  artifacts:
    when: always
    paths:
      - target/site/serenity
