stages:
  - build
  - test
  - deploy

# Build stage
build:
  image: maven:3.6-jdk-8
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar

# Test stage
test:
  image: maven:3.6-jdk-8
  stage: test
  script:
    - mvn test
  artifacts:
    paths:
      - target/test-*.xml
    when: always

# Deploy stage (example deploy to a server)
deploy:
  stage: deploy
  script:
    - echo "Deploying your app"
    # Add your deploy script here
  only:
    - main
